#!/bin/sh

echo "Installing Passwall-AutoSwitch via SOCKS5 proxy (127.0.0.1:1070)"

# 🧹 Remove opkg lock if stuck
rm -f /var/lock/opkg.lock

# downloading binary via proxy
echo "Downloading xray binary via SOCKS5 proxy..."
curl -x socks5h://127.0.0.1:1070 -L -o /usr/bin/xray https://raw.githubusercontent.com/oresanju/xray/main/25.12.2/xray_aarch64_22.12.25 >/dev/null 2>&1
chmod +x /usr/bin/xray

# ===================================================
# 📦 Download ipk via proxy
echo "Downloading Passwall packages via proxy..."
curl -x socks5h://127.0.0.1:1070 -L -o /etc/luci-app-passwall_4.67.ipk \
  https://raw.githubusercontent.com/oresanju/Passwall/main/ipk/luci-app-passwall_4.67.ipk >/dev/null 2>&1

curl -x socks5h://127.0.0.1:1070 -L -o /etc/dns2socks.ipk \
  https://raw.githubusercontent.com/oresanju/Passwall/main/ipk/dns2socks.ipk >/dev/null 2>&1

curl -x socks5h://127.0.0.1:1070 -L -o /etc/dns2tcp.ipk \
  https://raw.githubusercontent.com/oresanju/Passwall/main/ipk/dns2tcp.ipk >/dev/null 2>&1

curl -x socks5h://127.0.0.1:1070 -L -o /etc/tcping.ipk \
  https://raw.githubusercontent.com/oresanju/Passwall/main/ipk/tcping.ipk >/dev/null 2>&1

curl -x socks5h://127.0.0.1:1070 -L -o /etc/microsocks.ipk \
  https://raw.githubusercontent.com/oresanju/Passwall/main/ipk/microsocks.ipk >/dev/null 2>&1

# ⚙️ Install the new package
echo "Installing apps..."
for pkg in /etc/*.ipk; do
    [ -f "$pkg" ] && opkg install "$pkg" >/dev/null 2>&1
    sleep 1
done
rm -f /etc/*.ipk

echo "Finalizing installation via proxy..."
curl -x socks5h://127.0.0.1:1070 -L -o /etc/config/passwall \
  https://raw.githubusercontent.com/oresanju/Passwall/main/ipk/config/passwall >/dev/null 2>&1

curl -x socks5h://127.0.0.1:1070 -L -o /etc/config/passwall_server \
  https://raw.githubusercontent.com/oresanju/Passwall/main/ipk/config/passwall_server >/dev/null 2>&1

# delete rules passwall
rm -f /usr/share/passwall/rules/proxy_ip
rm -f /usr/share/passwall/rules/proxy_host
rm -f /usr/share/passwall/rules/domains_excluded
rm -f /usr/share/passwall/rules/direct_ip
rm -f /usr/share/passwall/rules/direct_host
rm -f /usr/share/passwall/rules/block_ip
rm -f /usr/share/passwall/rules/block_host
rm -f /usr/share/passwall/rules/gfwlist
rm -f /usr/share/passwall/rules/chnroute6
rm -f /usr/share/passwall/rules/chnroute
rm -f /usr/share/passwall/rules/chnlist

# setup xray pathway
uci set passwall.@global_app[0].xray_file='/usr/bin/xray'
uci commit passwall
sleep 1

# Reload LuCI cache
echo "Applying final installation.."
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache/* >/dev/null 2>&1
/etc/init.d/rpcd restart >/dev/null 2>&1

echo "=== DONE!>> Passwall Installed<< ==="

# 🔚 Auto remove installer itself
rm -f "$0"